version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - DEBUG=True
      - MONGO_DB=userdb
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
